Ticket/menu 19
iu-restaurant-app/restaurant-app-frontend pull request #23
Opened 2024-07-17 18:19 UTC by Aleliya

2024-07-17 22:54 UTC, almax07082005 requested changes
Have some minor fixes

2024-07-17 22:54 UTC, almax07082005 commented on src/app/page.tsx
the same situation is for admin/page.tsx and about-us/page.tsx. Fix those buttons' colors also

2024-07-17 22:54 UTC, almax07082005 commented on src/components/menu/menu-gallery.tsx
<img width="1512" alt="Screenshot 2024-07-18 at 1 50 51 AM" src="https://github.com/user-attachments/assets/daf41f5b-0b51-45d5-9d7c-a1c36aa6315a">
1. I can't see that you have reduced margin for small screens.
2. Make similar changes for loading state.
3. All changes that you will make for menu-gallery, apply to almost the same component in the admin package.

2024-07-17 23:04 UTC, almax07082005 commented
Also change margin bottom, check it for admin page also. To conclude, you should fix all two pages.

2024-07-19 08:56 UTC, mituttta051 requested changes
Minor changes has to be fixed

2024-07-19 08:56 UTC, mituttta051 commented on src/app/page.tsx
Шикарно, только на мобилках кнопка выезжает за пределы элемента, я подозреваю, это из-за того, что у него какая-то минимальная ширина стоит, надо ее меньше сделать
![telegram-cloud-photo-size-2-5246844770666535533-x](https://github.com/user-attachments/assets/326f2224-4897-48b4-b5e0-3964c1273060)

2024-07-19 08:56 UTC, mituttta051 commented on src/app/page.tsx
И вот тут еще косячок небольшой
<img width="418" alt="Screenshot 2024-07-19 at 11 55 48" src="https://github.com/user-attachments/assets/015e167d-2884-44a8-a2b0-8b7fe461d807">

2024-07-19 18:49 UTC, almax07082005 approved these changes
Good job

2024-07-19 18:51 UTC, merged