ticket/MENU-20
iu-restaurant-app/restaurant-app-frontend pull request #24
Opened 2024-07-17 19:17 UTC by arinapetukhova

Search bar logic was written. Navbar was added to the about-us page

2024-07-17 23:24 UTC, almax07082005 requested changes
just minor changes

2024-07-17 23:24 UTC, almax07082005 commented on src/app/about-us/page.tsx
Each time you change some common components, go through files and check for errors. For now build check was failed, you can find logs in checks sub page in the pull request because you have some mistakes in page.tsx, but it may be not the only one. After fixing, do not forget to push to the branch and check whether build is successful or not. Of course, before starting working UPDATE PROJECT.

2024-07-18 12:24 UTC, mituttta051 requested changes
Looks good, small fixes requested

2024-07-18 12:24 UTC, mituttta051 commented on src/app/page.tsx
<img width="1397" alt="image" src="https://github.com/user-attachments/assets/bd0dc742-d22c-42e2-b203-7a30df1b5640">
When no menu items were found you should show message "No meals were found"

2024-07-18 12:24 UTC, mituttta051 commented on src/components/about-us/navbar.tsx
Add to button styles: _transition-colors duration-300 ease-in-out_ to make smooth transition when hovered

2024-07-19 11:24 UTC, almax07082005 approved these changes
good job

2024-07-19 11:26 UTC, mituttta051 approved these changes
good job

2024-07-19 11:26 UTC, merged